spring.application.name=collabpro-platform
spring.profiles.default=local
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/identity
spring.jackson.deserialization.fail-on-unknown-properties=true
server.error.include-message=never
server.error.include-stacktrace=never
